name: "house_price_prediction"

# Model Configuration for House Price Prediction

# Data settings
data:
  target_column: "price"
  test_size: 0.2
  random_state: 42

# Model settings
model:
  name: "house_price_prediction"
  type: "random_forest"
  target_variable: "price"
  best_model: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

# Feature settings
features:
  numerical_features:
    - "sqft"
    - "bedrooms"
    - "bathrooms"
    - "year_built"
    - "house_age"
    - "price_per_sqft"
    - "bed_bath_ratio"
  
  categorical_features:
    - "location"
    - "condition"

# Training settings
training:
  cv_folds: 5
  scoring: "neg_mean_squared_error"
  save_model: true
  model_name: "house_price_predictor"

# MLflow settings
mlflow:
  experiment_name: "house_price_prediction"
  run_name: "random_forest_model"
  name: "house_price_prediction" 